from flask import Flask, request, jsonify

app = Flask(__name__)

# 단어와 뜻을 저장하는 사전
word_dict = {
    "innocent": "무해한; 무죄인, 결백한",
    "intangible": "무형의; 무형 자산",
    "integral": "필수적인; 완전한",
    "legitimate": "정당한; 합법적인",
    "leisurely": "느긋한; 느긋하게",
    "nomadic": "유목민의; 유목 생활을 하는",
    "procrastination": "(일을) 미루기; 지연",
    "reflex": "반사 작용, 반사 행동",
    "sibling": "형제자매, 동기",
    "soothing": "진정시키는, 달래는",
    "vulnerability": "취약성, 상처 받기 쉬움",
    "aboriginal": "원주민의, 토착민의",
    "authenticity": "진정성, 진품성",
    "affluent": "부유한, 풍부한",
    "analytical": "분석적인, 분석의",
    "archival": "기록(보관소)의, 고문서의",
    "authorize": "위임하다, 권한을 주다",
    "awkward": "(기분이) 어색한; (솜씨가) 서투른; (다루기) 곤란한",
    "tangled": "엉킨; 얽힌",
    "camouflage": "위장; 위장하다",
    "chronological": "시간 순으로 일어나는, 연대순의",
    "collision": "충돌 (사고), 부딪침",
    "controversial": "논란을 불러일으키는",
    "crave": "열망하다, 갈망하다",
    "freight": "화물 (운송)",
    "reign": "지배하다; 치세, 통치 (기간)",
    "yearn": "간절히 바라다, 갈망하다",
    "abhor": "혐오하다",
    "affiliate": "제휴하다; ~에 소속되다; 자회사",
    "affirmative": "긍정의, 동의의",
    "cuisine": "요리(법)",
    "pervasive": "만연하는, 널리 스며드는",
    "dignity": "존엄(성); 위엄",
    "precede": "~보다 먼저 일어나다, 선행하다",
    "discern": "식별하다, 분별하다, 인식하다",
    "pronounced": "두드러진, 현저한",
    "diversify": "다양화하다",
    "receptive": "수용적인, 선뜻 받아들이는",
    "extract": "추출하다; 발췌하다; 추출물; 발췌",
    "vista": "(아름다운) 경치, 전경; 예상, 전망",
    "faculty": "능력, 재능; 교수진, 교직원",
    "retreat": "물러나다; 후퇴; 휴양지",
    "fraction": "부분, 일부; 분수",
    "screech": "날카로운 소리를 내다; 날카로운 소리",
    "generalize": "일반화하다",
    "sedentary": "주로 앉아서 하는, 이주하지 않는",
    "gullible": "쉽게 속는",
    "stubborn": "고집 센, 완고한",
    "inefficient": "비효율적인",
    "thrust": "밀다; 찌르다; 찌르기; 추진력",
    "inferior": "열등한; 아랫사람의; 하급자, 열등한 사람",
    "alleviate": "(고통을) 경감하다, 완화하다",
    "homogeneous": "동질적인, 동종의",
    "commence": "시작하다, 시작되다",
    "internalize": "내면화하다, 내재화하다",
    "exemplar": "본보기, 모범",
    "justification": "정당성, 정당화",
    "wrench": "비틀어 떼어 내다; 삐다",
    "lethal": "치명적인",
    "entreaty": "간청, 애원",
    "transformation": "변신, 변화, 변형",
    "inhabitant": "거주자, 주민, 서식 동물",
    "transfusion": "수혈; (자금 등의) 투입",
    "insulate": "절연 처리하다; ~로부터 보호하다",
    "appliance": "(가정용) 전기 제품, 기기",
    "interconnected": "상호 연결된",
    "attentive": "주의 깊은, 주의를 기울이는",
    "masculine": "남성적인, 남성의",
    "aviation": "항공(술)",
    "milestone": "중요한 일[사건, 단계], 획기적 사건",
    "booster": "증폭기; (사기·자신감 등을) 높이는 것",
    "naive": "(경험·지식 부족으로) 순진한",
    "communal": "공동(체)의, 공용의",
    "peripheral": "주변의; (컴퓨터의) 주변장치",
    "comply": "순응하다, 따르다",
    "permanent": "영원한, 영속적인, 영구적인",
    "decelerate": "감속하다",
    "populate": "(어떤 장소에) 살다, 거주시키다",
    "definitive": "결정적인, 최종적인",
    "reinforcement": "(감정·생각 등 심리적인) 강화",
    "domesticate": "사육하다, 길들이다",
    "detest": "혐오하다",
    "inhibit": "막다, 억제하다, 방해하다",
    "allure": "유혹하다, 사로잡다",
    "immerse": "(액체에) 담그다; 몰두(하게)하다",
    "undeserved": "받을 자격이 없는, 과분한",
    "impoverish": "가난하게 만들다",
    "vanguard": "선구자, 선도자, 선봉",
    "impulsive": "충동적인, 즉흥적인",
    "tyrant": "폭군, 독재자"
}


@app.route('/get_meaning', methods=['GET'])
def get_meaning():
    word = request.args.get('word')
    meaning = word_dict.get(word)
    if meaning:
        return jsonify({"word": word, "meaning": meaning})
    else:
        return jsonify({"error": "단어를 찾을 수 없습니다."})

if __name__ == '__main__':
    app.run(debug=True)
